### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by IgoR-NiK** [IgoR-NiK/VK-API-Group-statistic#4]
Добавить SQLite для базы консультантов и выгрузку статистики о работе консультантов.

В Таблице Консультантов требуется хранить: Id, Имя, Фамилия, Аватарка, Факультет (ИФ, Аватарка, как их получить лучше?Во время добавления нового консультанта писать только Id и Факультет, а остальные данные подгрузить из вк?)
В Таблице Пользователей требуется хранить: ID,ФИ, Пол, Дата Рождения,Страна, Город, Статус + Факультеты(Факультеты можно одной строкой, я думаю)
В Таблице Данные с Сервера: Id, Имя, Фамилия, Вошел/Вышел, время

**Comment by IgoR-NiK** [comment]
В Таблице Консультантов требуется хранить: Id, Имя, Фамилия, Аватарка, Факультет (ИФ, Аватарка, как их получить лучше?Во время добавления нового консультанта писать только Id и Факультет, а остальные данные подгрузить из вк?)
В Таблице Пользователей требуется хранить: ID,ФИ, Пол, Дата Рождения,Страна, Город, Статус + Факультеты(Факультеты можно одной строкой, я думаю)
В Таблице ДанныеССервера: Id, Имя, Фамилия, Вошел/Вышел, время

**Comment by JustickDM** [comment]
Реализовано.

**Comment by JustickDM** [comment]
Реализовано.
